### ISSUE TITLE
Missing run dir causes obscure error

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-mc#278]
When run dir is left out of the command for running pool this error occurs:

```Traceback (most recent call last):
  File "/home/jeremym/hps-work/hps-mc/install/lib/python/hpsmc/batch.py", line 651, in <module>
    batch.submit()
  File "/home/jeremym/hps-work/hps-mc/install/lib/python/hpsmc/batch.py", line 602, in submit
    cmd = self.build_cmd(job_id, job_data)
  File "/home/jeremym/hps-work/hps-mc/install/lib/python/hpsmc/batch.py", line 202, in build_cmd
    job_dir = os.path.join(self.run_dir, str(job_id))
  File "/apps/python/PRO/lib/python3.4/posixpath.py", line 82, in join
    path += b
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

Instead, a default directory should be used or an exception should be thrown.

**Comment by JeremyMcCormick** [comment]
The linked PR should fix this (or an earlier change did).
