### ISSUE TITLE
fieldmap setup for JavaTool

### ISSUE THREAD

**Issue by sarahgaiser** [JeffersonLab/hps-mc#325]
Problem:
```
bravo@sdf-login04:~/test$ java -cp /sdf/home/b/bravo/.m2/repository/org/hps/hps-distribution/5.2-SNAPSHOT/hps-distribution-5.2-SNAPSHOT-bin.jar org.hps.util.ExtractEventsWithHitAtHodoEcal -e 250 /sdf/group/hps/users/sgaiser/run/ali_invest/const_field/tritrig/HPS_Nominal_3pt74GeV/slic/tritrig/output/3pt74/tritrig_3pt74_8pt75um50nA_rot_1.slcio tritrig_cat.slcio
Reading default logging config from logging.properties
Opened input file /sdf/group/hps/users/sgaiser/run/ali_invest/const_field/tritrig/HPS_Nominal_3pt74GeV/slic/tritrig/output/3pt74/tritrig_3pt74_8pt75um50nA_rot_1.slcio
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.lcsim.geometry.Subdetector.getName()" because "detector" is null
	at org.lcsim.event.base.SamplingFractionManager.getCorrectedEnergy(SamplingFractionManager.java:34)
	at org.lcsim.event.base.BaseCalorimeterHit.calculateCorrectedEnergy(BaseCalorimeterHit.java:120)
	at org.lcsim.lcio.SIOSimCalorimeterHit.<init>(SIOSimCalorimeterHit.java:68)
	at org.lcsim.lcio.SIOSimCalorimeterHitBlockHandler.addCollectionElements(SIOSimCalorimeterHitBlockHandler.java:23)
	at org.lcsim.lcio.AbstractBlockHandler.readCollection(AbstractBlockHandler.java:39)
	at org.lcsim.lcio.AbstractBlockHandler.readBlock(AbstractBlockHandler.java:32)
	at org.lcsim.lcio.LCIOReader.read(LCIOReader.java:77)
	at org.hps.util.ExtractEventsWithHitAtHodoEcal.main(ExtractEventsWithHitAtHodoEcal.java:129)
```

When does this happen:
Using a 'new' fieldmap that is not on the master branch of the hps-fieldmap repo but present locally in hps-fieldmaps

Underlying problem:
No link to the fieldmap directory is created when running `ExtractEventsWithHitAtHodoEcal` (or any JavaTool) with hps-mc. Usually, the fieldmap is then downloaded from github from hps-fieldmaps. If the fieldmap is not on the master branch of this repo, this step fails and we have neither link nor copy of the fieldmap in the run directory.

How to fix it:
Add process of linking the fieldmaps directory to `JavaTool`, analogously to how it's done for `SLIC` in `hps-mc/python/hpsmc/tools.py`.

**Comment by JeremyMcCormick** [comment]
Another way to fix this is pointing hps-mc at your hps-java bin jar which contains the field map that is not in master via the .hpsmc config file.
